# =============================================
# Build config
# =============================================

root:             _output
dest:             <%= site.root %>
assets:           <%= site.dest %>/assets

# Data
data:             data/*.{json,yml}
content:          content

# Templates
templates:        templates
includes:         <%= site.templates %>/includes/*.hbs
layouts:          <%= site.templates %>/layouts
layout:           default.hbs

# Extensions
helpers:
  - handlebars-helper-br
  - handlebars-helper-slugify

plugins:
  - assemble-contrib-anchors
  - assemble-contrib-toc

# Theme
theme:            theme
components:       <%= site.theme %>/components


# =============================================
# Project metadata
# =============================================

# Assemble metadata.
assemble:
  latest:         0.4.33  # change to <%= pkg.version %>

# GitHub
username:         sensics
name:             <%= pkg.name %>
download:
  source:         <%= pkg.homepage %>/archive/master.zip


# =============================================
# Site metadata
# =============================================

brand:            OSVR
title:            Device Descriptor Editor

version:          <%= pkg.version %>
description:      <%= pkg.description %>
license:
  type:           <%= pkg.licenses[0].type %>
  url:            <%= pkg.licenses[0].url %>


# Links
url:
  repo:           <%= pkg.homepage %>
  bugs:           <%= pkg.bugs.url %>?state=open
